name: chatapp
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.0.1
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  smooth_page_indicator: ^0.2.3
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.5
  floating_navbar: ^2.0.1
  image_picker: any
  curved_navigation_bar: any
  firebase_messaging: any
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/

  fonts:
    - family: AkayaKanadaka
      fonts:
        - asset: fonts/AkayaKanadaka-Regular.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf

